---
- name: Build Quazi Image
  hosts: localhost
  gather_facts: false
  become: true
  become_method: sudo

  tasks:
    - name: upgrade all packages
      apt:
        name: '*'
        state: latest

  roles:
    - quazi
