---
# tasks file for quazi

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-opencv 
    - nginx
    - unicorn
    - curl 
    - gnupg 
    - build-essential
    - python-pip
    - python-dev

# Install Python 2.7.12
#- name: Download Python 2.7.12
#  get_url: dest=/var/local/ansible-cache url=http://www.python.org/ftp/python/2.7.12/Python-2.7.12.tar.xz 
#  sudo: yes

#- name: Ensure Python 2.7.12 is extracted
#  shell: chdir=/var/local/ansible-cache tar xJf ./Python-2.7.12.tar.xz -C /opt creates=/opt/Python-2.7.12
#  sudo: yes

#- name: Ensure Python 2.7 is configured
#  shell: chdir=/opt/Python-2.7.12 ./configure --prefix=/opt/python2.7

#- name: Ensure Python 2.7 make'd
#  shell: chdir=/opt/Python-2.7.12 make

#- name: Ensure Python 2.7 installed
#  shell: chdir=/opt/Python-2.7.12 make install
#  sudo: yes

- name: Install the packages specified in requirements.txt
  pip: requirements=/tmp/workspace/ulta-image-hardening/quazi/req.txt

